import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from '@/context/AuthContext'
import { Suspense } from 'react'
import { CircularProgress } from '@mui/material';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <Provider>
          <Suspense fallback={ <CircularProgress size={100}/>}>{children}</Suspense>
        </Provider>
      </body>
    </html>
  )
}

